### ISSUE TITLE
Drush install for Drupal 8.4+ and Drush 9

### ISSUE THREAD

**Issue by christopher-hopper** [geerlingguy/ansible-role-drush#41]
## Problem/Motivation

Drupal 8.4.x requires use of Drush 9. Drush 9 deprecates support for global installation methods using a `drush.phar` download or Composer global require. Further to this, Drush 9 will no longer support use of a `.drush-use` file and associated wrapper script, that points to a project Drush dependency.

## Suggested Solution

The officially supported solution to running Drush from anywhere in a Project's path is the Drush Launcer command. It may be worth moving to that now.

1. Install the [Drush Launcher](https://github.com/drush-ops/drush-launcher) (formerly `webflo/drush-shim`) instead of a `drush.phar`. This would prepare the Vagrant DrupalVM and other users of this ansible role for Drupal 8.4.x and Drush 9. 

    ```diff
    diff --git a/defaults/main.yml b/defaults/main.yml
    index 704fb3f..7e8a25b 100644
    --- a/defaults/main.yml
    +++ b/defaults/main.yml
    @@ -1,7 +1,7 @@
     ---
     # Install from phar (faster, but less flexible).
    -drush_version: "8.1.10"
    -drush_phar_url: https://github.com/drush-ops/drush/releases/download/{{ drush_version }}/drush.phar
    +drush_launcher_version: "0.3.1"
    +drush_phar_url: https://github.com/drush-ops/drush-launcher/releases/download/{{ drush_launcher_version }}/drush.phar
     drush_path: /usr/local/bin/drush
    
     # Install from source (git clone + composer-based install).
    ```

2. Remove the option to install from source? 

The Drush Launcher works with project installed versions of Drush 8, Drush 9, and future versions of Drush. 

## Related Links

- [Drush: Docs » General » Install](http://www.drush.org/en/master/install/#install-a-site-local-drush-and-drush-launcher)
- https://github.com/drush-ops/drush/issues/2699#issuecomment-320305506

**Comment by geerlingguy** [comment]
Ugh, I'm just getting up to speed on all this, and it makes installing/using Drush way more complicated than in the past :(

I mean, I get it, Drush is moving more and more towards being a composer dependency only (I guess 9.0.0 is the final step in that transition)... but it's hell to support a wide array of Drupal sites with Drupal 8.4 + Drush 9.0.0 being somewhat of a requirement (though I'm still using 8.1.15 as much as I can).

**Comment by geerlingguy** [comment]
I think the way I'll take this role is:

  1. Default to installing drush-launcher (since that's preferred moving forward and should be default according to what I've read in Drush docs and issues).
  2. Allow installation of Drush via Composer globally (note this limits global Drush usage to a single user, e.g. `root`/`sudo` if installed as the root user...).
  3. Keep the current source installation functionality.

Because this is pretty much a radical rewrite of the role, and changes the way everything behaves, version number will go up to 3.x.

And if we find out that this is a horrible idea (I haven't fully integrated changes with something like Drupal VM yet which uses Drush in many and various ways...), we'll have to either ditch 3.x and go back to 2.x, or move on to a new idea/structure in 4.x.

I definitely think drush-launcher is the preferred option, as it seems like that's what Drush 9.0+ will prefer very strongly. I'm just worried that I'm going to have to start neglecting poor Drupal 7 and lower users once I start moving things fully over to this new world...
